version: "1"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
exclude_patterns:
- node_modules/
- "**/__tests__/"
- ".codeclimate.yml"
- "**/*.html"
- "**/*.md"
- "**/*.json"
- "yarn.lock"
- "public/"
- ".eslintrc"
- ".eslintignore"
- ".gitignore"
- ".prettierrc"